name: fcr_results_downloader_poetry
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: transform
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
