name: fcr_results_downloader
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: regelleistung-justresults
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
